### ISSUE TITLE
Nbconvert as Github action

### ISSUE THREAD

**Issue by tschm** [jupyter/nbconvert#1287]
I am trying to create html documents of my notebooks using a Github action

A beautiful neat Github action

I have tried the following

```
FROM jupyter as slides

COPY --chown=jovyan:100 ./work $WORK

RUN mkdir /home/$NB_USER/slides && \
    chown -R jovyan:100 /home/$NB_USER/slides

CMD jupyter nbconvert --output-dir=/home/$NB_USER/slides /home/$NB_USER/work/*.ipynb --to html

```
This can be triggered locally but I get permission problems even as root on github. Maybe you have experience with that problem

**Comment by tschm** [comment]
got it
```
name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert

      - name: Convert Notebooks
        run: |
          jupyter nbconvert --output-dir=./slides ./binder/files/*.ipynb --to html

      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          # declare the artifacts...
          name: slides
          path: slides
```
