### ISSUE TITLE
[WebPDF] `@media print` CSS rules for WebPDF export

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/nbconvert#1404]
The classic template includes the following CSS:

```css
@media print {
  div.cell {
    display: block;
    page-break-inside: avoid;
  }
  div.output_wrapper {
    display: block;
    page-break-inside: avoid;
  }
  div.output {
    display: block;
    page-break-inside: avoid;
  }
}
```

These rules are used when exporting to PDF using the webpdf exporter.

We should probably have a similar CSS rule for the `lab` template, and another one *introducing* page breaks between sections for the `reveal` template, in order to separate slides into different pages when exporting to PDF.

Potentially, the content of the CSS could be in a jinja macro.
