### ISSUE TITLE
Lab template output content is misaligned with prompt

### ISSUE THREAD

**Issue by dakoop** [jupyter/nbconvert#1794]
Bascially, the output content doesn't align properly with the prompt, causing a mismatch with JupyterLab and a noticeable misalignment (look at `[8]: 6300.0`). In the screenshots, the nbconvert output is shown first, then the JupyterLab rendering:

![Notebook in nbconvert showing misalignment](https://user-images.githubusercontent.com/2249780/172927775-01c876a5-89b4-418f-9856-dfc6e3a843a2.png)
![Same notebook in JupyterLab with proper alignment](https://user-images.githubusercontent.com/2249780/172927765-749c7eb6-0748-4947-b7cf-36abc5050a0d.png)

This is due to the `padding-top` not being added. The relevant css rule from JupyterLab is 
```css
.jp-OutputArea-executeResult .jp-RenderedText.jp-OutputArea-output {
  padding-top: var(--jp-code-padding);
  border-top: var(--jp-border-width) solid transparent;
}
```
which means an element classed as `.jp-RenderedText.jp-OutputArea-output` must be a descendant of one classed as `.jp-OutputArea-executeResult`. In `share/templates/lab/index.html.j2`, the relevant class is added here:

https://github.com/jupyter/nbconvert/blob/58b0ae2cebfc550d0042a29ca9c3e1b62da78c66/share/templates/lab/base.html.j2#L112-L118

but this is added on the `.jp-OutputArea-output` element instead of its parent element to trigger the rule.

Potentially related to #1145.

**Nbconvert version:** 6.5.0
