### ISSUE TITLE
HTML export removes text color in @media print CSS statement

### ISSUE THREAD

**Issue by gcbgit** [jupyter/nbconvert#189]
The HTML embedded styles include this line:

``` css
@media print{*,:after,:before{background:0 0!important;color:#000!important;box-shadow:none!important;text-shadow:none!important}
```

which turns off all syntax coloring in printed output.  The !important attributes make it impossible to override locally.  Text coloring certainly shouldn't be turned off by default, and even things like the shadows should be left under user control.
