### ISSUE TITLE
Broken CSS background color(s) for code blocks in Markdown cells

### ISSUE THREAD

**Issue by mgeier** [jupyter/nbconvert#299]
There are three different background colors in code blocks:

First, on the surrounding `<div>`, which probably comes from the syntax highlighter:

```css
.highlight {
    background: #f8f8f8;
}
```

Then, on the `<pre>`, which I guess comes from bootstrap:

```css
pre {
    background-color: #f5f5f5;
}
```

... which is overruled by this:

```css
.rendered_html pre, .rendered_html code {
    background-color: #fff;
}
```

I guess the intention was to have a white background everywhere, but the problem is that the surrounding `<div>` is wider than the `<pre>`, which leads to (barely) visible light grey blocks on both sides.
