### ISSUE TITLE
Why is the notebook CSS not the latest 5.x ?

### ISSUE THREAD

**Issue by oscar6echo** [jupyter/nbconvert#679]
It is a pity because pandas dataframes in nbconvert default output look bad now - compared to the 5.x notebook.  For my own use I can customize nbconvert and manually add the latest CSS - as in this [nbconvert-custom repo](https://github.com/oscar6echo/nbconvert-custom).  
But nbviewer does not update and it is a bit disappointing.  

I want to make clear that nbconvert and nbviewer are fantastic tools. And I don't intend to criticize. Probably people are busy. Or is maybe there a specific reason ? 

I'd be curious to know.

**Comment by takluyver** [comment]
I think it just needs to be updated - I don't know of any reason we're using an older version.

**Comment by oscar6echo** [comment]
So I proposed a pull request to update the version.  
But it 1 test failed. With Python 3.5. See the [travis job report](https://travis-ci.org/jupyter/nbconvert/jobs/279026100).  
The error report is not very clear to me. Any idea why ?

**Comment by takluyver** [comment]
Closed by #682 .

Sometimes stuff fails randomly on Travis, in which case rerunning usually makes it work. It's unfortunate, but that's the way things go.

**Comment by oscar6echo** [comment]
After mentioning the problem in #689 I looked further into it.
I think the merge did not work well.  
A build problem ?  

The main purpose was to update a css file from [notebook css version 4.3.1](https://cdn.jupyter.org/notebook/4.3.0/style/style.min.css) to [version 5.1.0](https://cdn.jupyter.org/notebook/5.1.0/style/style.min.css).  
The reason was the better rendering of tables (pandas dataframes) in the latter.  
Some key lines are:
```css
/* https://cdn.jupyter.org/notebook/4.3.0/style/style.min.css */
/* starting line 10257 */
.rendered_html table {
    margin-left: auto;
    margin-right: auto;
    border: 1px solid black;
    border-collapse: collapse;
  }
/* https://cdn.jupyter.org/notebook/5.1.0/style/style.min.css */
/* starting line 11120 */
 .rendered_html table {
    margin-left: auto;
    margin-right: auto;
    border: none;
    border-collapse: collapse;
    border-spacing: 0;
    color: black;
    font-size: 12px;
    table-layout: fixed;
  }
```

You can check that when you install nbconvert, the second section is not there, and the first still around - in file `site-packages/nbconvert/resources/style.min.css.`  

As an additional clue the timestamp for file nbconvert/resources/style.min.css is 5 sep 17, which is before the merge (24 sep 17).

This is surprising as the only indication of which css file to use is [line 69 in setup.py](https://github.com/jupyter/nbconvert/blob/4abde40750ee9adf666e5d6cb693d086566a390c/setup.py#L69) - and it's the only line modified by [PR682](https://github.com/jupyter/nbconvert/pull/682).  

Somehow the following cmdclass defined in [line 127](https://github.com/jupyter/nbconvert/blob/4abde40750ee9adf666e5d6cb693d086566a390c/setup.py#L127) and used in setup in [line 167](https://github.com/jupyter/nbconvert/blob/4abde40750ee9adf666e5d6cb693d086566a390c/setup.py#L167) did not work as expected...?

Anyway how to correct this ?
And maybe explain what happened ??
